# Generated by Django 5.2.7 on 2026-03-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_add_predicted_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
